### ISSUE TITLE
Trouble with launching

### ISSUE THREAD

**Issue by GarrisonD** [smelukov/webpack-runtime-analyzer#13]
Hi! I have some troubles with using your module.

I am using the latest version `1.4.1` of your library and `webpack 2.3.3` and next plugin configuration:

```
plugins: [
  ...
  new RuntimeAnalyzerPlugin()
]
```

And I see such errors in console:

```
$ webpack-dev-server 
Starting rempl server...
Project is running at http://localhost:8080/
webpack output is served from /
~/webpack-demo/node_modules/webpack-runtime-analyzer/src/plugin/index.js:166
                plugin.publisher.sync();
                                 ^

TypeError: plugin.publisher.sync is not a function
    at ChildProcess.<anonymous> (~/webpack-demo/node_modules/webpack-runtime-analyzer/src/plugin/index.js:166:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error Command failed with exit code 1.
```

Do you have any ideas? 🙂

**Comment by smelukov** [comment]
Hi! Can't reproduce it (
Which versions of `npm` and `node` do you use?
Can you exec `cat node_modules/rempl/package.json` from your project root and show the result?

**Comment by smelukov** [comment]
Also, you can exec:
```sh
npm uninstall webpack-runtime-analyzer
npm install webpack-runtime-analyzer@1.4.0
```
And try to start a building again

**Comment by GarrisonD** [comment]
```
$ cat node_modules/rempl/package.json
{
  "name": "rempl",
  "version": "1.0.0-alpha9",
  "description": "Рlatform for moderated remote access to JavaScript runtime via custom UI",
  "main": "src/index.js",
  "author": "Roman Dvornov",
  "contributors": [
    "Roman Dvornov <rdvornov@gmail.com>",
    "Sergey Melyukov <s.melukov@gmail.com>",
    "Anastasia Goryacheva <a.e.goryacheva@gmail.com>"
  ],
  "license": "MIT",
  "repository": "rempl/rempl",
  "homepage": "https://github.com/rempl/rempl",
  "bugs": {
    "url": "https://github.com/rempl/rempl/issues"
  },
  "eslintConfig": {
    "env": {
      "node": true,
      "mocha": true,
      "es6": true
    },
    "rules": {
      "no-duplicate-case": 2,
      "no-undef": 2,
      "no-unused-vars": [2, {"vars": "all", "args": "after-used"}]
    }
  },
  "main": "src/index.js",
  "scripts": {
    "codestyle": "jscs src server && eslint src server",
    "build": "npm run build:rempl && npm run build:server-assets",
    "build:rempl": "browserify --standalone rempl src/index.js | uglifyjs --compress --mangle -o dist/rempl.js",
    "build:server-assets": "node node_modules/basisjs-tools-build/bin/build -c server/client/build.config",
    "prepublish": "npm run build"
  },
  "devDependencies": {
    "basisjs": "~1.10.0",
    "browserify": "^13.0.0",
    "eslint": "^3.11.1",
    "jscs": "~3.0.7",
    "uglify-js": "^2.6.1",
    "basisjs-tools-build": "^1.4.0"
  },
  "dependencies": {
    "chalk": "~1.1.3",    
    "socket.io-client": "^1.7.1"
  },
  "files": [
    "dist",
    "server",
    "src",
    "HISTORY.md",
    "LICENSE",
    "README.md"
  ]
}
```

**Comment by GarrisonD** [comment]
```
$ npm -v
4.4.4
```
```
$ node -v
v7.8.0
```

**Comment by GarrisonD** [comment]
Sorry, there was a trouble with Yarn. After reinstalling deps with `npm` everything works fine. 😉

**Comment by smelukov** [comment]
Yes, yarn may have some problems with installing some packages ;)

**Comment by smelukov** [comment]
As you see, yarn installed rempl alpha 9 instead of 14
