### ISSUE TITLE
Error: loaderUtils.parseQuery is not a function

### ISSUE THREAD

**Issue by 4muzar** [smelukov/webpack-runtime-analyzer#9]
Plugin crashes when used new version of `"loader-utils"`(e.g. `1.0.3`)

Stack trace
```
TypeError: loaderUtils.parseQuery is not a function
    at /Users/avsavchenko/projects/road-frontend/node_modules/webpack-runtime-analyzer/src/plugin/index.js:99:35
    at Array.map (native)
    at getModuleLoaders (/Users/avsavchenko/projects/road-frontend/node_modules/webpack-runtime-analyzer/src/plugin/index.js:91:35)
    at /Users/avsavchenko/projects/road-frontend/node_modules/webpack-runtime-analyzer/src/plugin/index.js:202:30
    at Array.map (native)
    at RuntimeAnalyzerPlugin.<anonymous> (/Users/avsavchenko/projects/road-frontend/node_modules/webpack-runtime-analyzer/src/plugin/index.js:158:43)
    at next (/Users/avsavchenko/projects/road-frontend/node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.<anonymous> (/Users/avsavchenko/projects/road-frontend/node_modules/webpack/lib/ProgressPlugin.js:127:4)
    at Compiler.applyPluginsAsyncSeries (/Users/avsavchenko/projects/road-frontend/node_modules/tapable/lib/Tapable.js:142:13)
    at Compiler.emitAssets (/Users/avsavchenko/projects/road-frontend/node_modules/webpack/lib/Compiler.js:292:7)
    at onCompiled (/Users/avsavchenko/projects/road-frontend/node_modules/webpack/lib/Compiler.js:53:18)
    at /Users/avsavchenko/projects/road-frontend/node_modules/webpack/lib/Compiler.js:480:13
    at next (/Users/avsavchenko/projects/road-frontend/node_modules/tapable/lib/Tapable.js:138:11)
    at Compiler.<anonymous> (/Users/avsavchenko/projects/road-frontend/node_modules/webpack/lib/CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (/Users/avsavchenko/projects/road-frontend/node_modules/tapable/lib/Tapable.js:142:13)
    at /Users/avsavchenko/projects/road-frontend/node_modules/webpack/lib/Compiler.js:477:10

```

**Comment by smelukov** [comment]
Thanks! I'll fix it

**Comment by smelukov** [comment]
Fixed.
Will be included in the near release
